language: node_js
node_js:
  - "0.10"
  - 0.11
matrix:
  allow_failures:
    - node_js: 0.11
notifications:
  email:
    - mosconfabrizio@gmail.com
env:
  global:
    - NODE_ENV=testing
    - SERVER_API_LISTENPORT=4000
    - SERVER_API_LISTENHOST='0.0.0.0'
    - SERVER_ENABLETESTCONTROLLER=false
    - SERVER_AUTH_SALTLENGTH=8
    - SERVER_SESSION_SECRET="ergerergreegregregrklheruio3489y3489y3489y3489h"
    - LOGGER_ENABLESRC=false
    - LOGGER_STDOUT_ENABLED=false
    - LOGGER_STDOUT_LEVEL='trace'
    - LOGGER_STDERR_ENABLED=false
    - LOGGER_STDERR_LEVEL='error'
    - LOGGER_RINGBUFFER_ENABLED=false
    - LOGGER_RINGBUFFER_LEVEL='trace'
    - LOGGER_RINGBUFFER_LIMIT=100
    - LOGGER_SYSLOG_ENABLED=false
    - LOGGER_SYSLOG_LEVEL='info'
    - LOGGER_SYSLOG_STREAM_TYPE=null
    - LOGGER_SYSLOG_STREAM_FACILITY=null
    - LOGGER_SYSLOG_STREAM_HOST=127.0.0.1
    - LOGGER_SYSLOG_STREAM_PORT=0
    - DB_MONGO_HOST="127.0.0.1"
    - DB_MONGO_PORT="27017"
    - DB_MONGO_DBNAME="test-arco"
    - DB_MONGO_USER=""
    - DB_MONGO_PASSWORD=""
    - REDIS_HOST=127.0.0.1
    - REDIS_PORT=6379
    - REDIS_PASSWORD=''
