#!/bin/bash

# This is a simple wrapper for setting enviroment variables before
# running scripts. We do this to allow dev etc to closely mimic the
# way production, staging, etc work and to allow developers to have
# their own custom env setting without commiting them to the repo
#
# Usage :
# ./set-env [env-name] {command} [{arg1} {arg2} {...}]
#
# e.g:
# ./set-env fab npm start
# ./set-env node bootsrapper.js
#
# The first [optional] argument is the name of the enviroment to load up. For a
# given name the path `./env/{ENV_NAME}.conf` is looked up.
# the next argument is the command you want to run. Any further arguments are
# passed through to the command
#
# An example enviroment file is included at ./env/local.conf
# which will be loaded by default if the first arguement isn't
# a path to a enviroment file. If you want change any settings
# just for your own enviroment you should copy that file and edit the
# copied file. Please don't commit the duplicated file to git...


# exit if anything goes wrong
set -e


# Usage message that is displayed when `--help` is given as an argument.
usage() {
  echo "Usage: ./set-env [<envvar file>] command args1 args2"
  echo "Run things with env vars"
  echo
  echo "This script reads commands from <envvar file> and runs the command"
  echo "you specify afterwards"
}

# If the --help option is given, show the usage message and exit.
expr -- "$*" : ".*--help" >/dev/null && {
  usage
  exit 0
}

envfile=("$@")

if [ -r src/env/$envfile.conf ]
then
  ENVFILE=src/env/$envfile.conf
  shift
else
  ENVFILE=src/env/local.conf
fi

while read line || [ -n "$line" ]; do
  if [[ "$line" != \#* ]] && [[ "$line" == *=* ]]; then
    eval "export $line"
  fi
done < "$ENVFILE"


"$@"


