// Generated by CoffeeScript 1.6.2
(function() {
  var User;

  User = require('src/model/User');

  User = (function() {
    function User() {}

    User.marshall = function(user) {
      if (!(user instanceof User)) {
        throw new Error('Invalid user');
      }
      return user;
    };

    User.unmarshall = function(data) {
      if (data == null) {
        throw new Error('Invalid user data');
      }
      return data;
    };

    return User;

  })();

  module.exports = User;

}).call(this);
